name: 'Lab01 Research Action'
description: 'Performs automated research tasks for Lab01'
inputs:
  research:
    description: 'Research name'
    required: true
  lab_name:
    description: 'Lab name'
    required: true
outputs:
  new_results:
    description: 'New results'
    value: ${{ steps.research.outputs.new_results }}
  processed_results:
    description: 'Processed results'
    value: ${{ steps.research.outputs.processed_results }}

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: Prepare environment
      run: |
        id -a
        go install github.com/OJ/gobuster/v3@latest
        gobuster version
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y
        yq --version
      shell: bash
    - name: Execute research script
      id: research
      run: |
        set -e
        ./${{ inputs.lab_name }}/execute.sh ${{ inputs.research }}
        set +e
      shell: bash
