name: 'Lab01 Research Action'
description: 'Performs automated research tasks for Lab01'
inputs:
  lab:
    description: 'Lab name'
    required: true
  research:
    description: 'Research name'
    required: true
  research_target:
    description: 'Base64 encoded research target URL'
    required: true
  processing_amount:
    description: 'Number of items to process'
    required: true
  exclude_response_length:
    description: 'Response length to exclude'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: Prepare environment
      run: |
        id -a
        go install github.com/OJ/gobuster/v3@latest
        gobuster version
      shell: bash
    - name: Execute research script
      run: |
        set -e
        ./${{ inputs.lab }}/start.sh ${{ inputs.lab }} ${{ inputs.research }} ${{ inputs.research_target }} ${{ inputs.processing_amount }} ${{ inputs.exclude_response_length }}
        set +e
      shell: bash
