name: init research

on:
  workflow_dispatch:
    inputs:
      lab_name:
        description: 'lab name'
        required: true
        default: 'lab01'
      research_target:
        description: 'research target (url)'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init research
        run:
          ${{ inputs.lab_name }}/init.sh ${{ inputs.research_target }}
      - name: Commit
        shell: bash
        run:  |
          set -x
          current=$(date)
          git config --global user.name 'scientist'
          git config --global user.email 'scientist@amazingandyyy.com'
          git status
          git add ${{ inputs.lab_name }}
          git commit -m "feat(${{ inputs.lab_name }}): init research on ${{ inputs.research_target }}" -m "$current"
          git pull --rebase && git push
          set +x
