name: lab01

env:
  lab_name: lab01

on:
  schedule:
    - cron: '0 * * * *' # every 1 hour
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/lab01.yaml'
      - '.github/actions/lab01'
      - 'lab01/**/*.sh'
      - 'lab01/**/instruction.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  find-research-projects:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Find directories with instruction.yaml
        id: find-directories
        run: |
          dirs=$(find ${{ env.lab_name }} -type f -name 'instruction.yaml' -exec dirname {} \; | while read -r line; do basename "$line"; done)
          if [ -z "$dirs" ]; then
            # If no directories are found, output an empty JSON array
            echo "matrix=[]" >> "$GITHUB_OUTPUT"
          else
            # Convert newline-separated list of directory names into a JSON array
            dirs_array=$(echo "$dirs" | jq -R -s -c 'split("\n")[:-1] | map(select(. != ""))')
            echo "Found directories: $dirs_array"
            echo "matrix=$dirs_array" >> "$GITHUB_OUTPUT"
          fi
      - name: Set matrix for job consumption
        id: set-matrix
        run: echo 'matrix=${{ steps.find-directories.outputs.matrix }}' >> "$GITHUB_OUTPUT"

  research:
    needs: find-research-projects
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        research: ${{ fromJson(needs.find-research-projects.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run research job
        id: research
        uses: ./.github/actions/lab01
        with:
          lab_name: ${{ env.lab_name }}
          research: ${{ matrix.research }}
      - name: diff
        id: diff
        shell: bash
        run: |
          git diff
          if [[ $(git diff --stat) != '' ]]; then
            echo "files_changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: commit
        if: steps.diff.outputs.files_changed == 'true'
        shell: bash
        run:  |
          set -x
          current=$(date)
          git config --global user.name 'scientist'
          git config --global user.email 'scientist@amazingandyyy.com'
          git status
          git add ${{ env.lab_name }}/researches/${{ matrix.research }}
          git commit -m "feat(${{ env.lab_name }}/${{ matrix.research }}): ${{ steps.research.outputs.new_results }}/${{ steps.research.outputs.processed_results }} positive results" -m "$current"
          git pull --rebase && git push
          set +x
